### ISSUE TITLE
Rationale for filter in initial query

### ISSUE THREAD

**Issue by PaulZH** [Swirrl/cubiql#154]
When the CubiQL endpoint connects to the SPARQL endpoint, it seems to fire following SPARQL query.
```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?ds ?name ?title ?description ?licence ?issued ?modified ?publisher 
WHERE {
  { SELECT DISTINCT ?ds 
    WHERE {  ?ds a qb:DataSet .} }  
  ?ds <http://www.w3.org/2000/01/rdf-schema#label> ?name .  
  FILTER(LANG(?name) = "")}
```
which in our case doesn't return anything, since in our case label values have a language attached.

I don't see this constraint anywhere documented.

**Comment by zeginis** [comment]
At the Cubiql configuration file use `:schema-label-language en`. You can use the any language tag except from `en`.

**Comment by PaulZH** [comment]
@zeginis Where do I find the documentation on cubiql-config.edn

**Comment by zeginis** [comment]
Here: https://github.com/Swirrl/graphql-qb/blob/master/doc/table2qb-cubiql.md

See at the bottom of page

**Comment by PaulZH** [comment]
Is this something from after release 0.4 ?

**Comment by PaulZH** [comment]
Is it possible to ask to return labels according to the preferences of and from the client? 

```
{cubiql{
  datasets {
    uri
    title <-- language returned based on user choice
    dimensions{
   	 uri}
  } 
}}
```

**Comment by lkitching** [comment]
@PaulZH - You can specify the language tag to use in the query with `lang_preference` e.g.

```sparql
{cubiql(lang_preference: "fr"){
  datasets {
    uri
    title
    dimensions{
   	 uri}
  } 
}}
```

**Comment by zeginis** [comment]
@PaulZH  is this issue fixed by using the `lang_preference` ?

**Comment by PaulZH** [comment]
For most use cases, yes.

Kind regards,

Paul Hermans
ProXML
(t) +32 15 23 00 76
(m) paul@proxml.be<mailto:paul@proxml.be>
(w) www.proxml.be<http://www.proxml.be>


On 30 Oct 2018, at 17:01, zeginis <notifications@github.com<mailto:notifications@github.com>> wrote:


@PaulZH<https://github.com/PaulZH> is this issue fixed by using the lang_preference ?

**Comment by zeginis** [comment]
This is fixed.
